const LOGIN = 'LOGIN';
const SIGN_UP = 'SIGN_UP';
const ADD_EXPENSE = 'ADD_EXPENSE';
const GET_DATA = 'GET_DATA';
const GET_DETAILS = 'GET_DETAILS';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
const LOGOUT = 'LOGOUT';

export {
    LOGIN,
    SIGN_UP,
    ADD_EXPENSE,
    GET_DATA,
    GET_DETAILS,
    DELETE_EXPENSE,
    UPDATE_EXPENSE,
    LOGOUT
};